DBNAME = 'Base'
TRUSTED_CONNECTION = 'yes'

TEST = False

STRING_CONNECTION = ''

SERVER = 'SERVER\SQLEXPRESS'
STRING_CONNECTION = 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=' + \
    SERVER+';DATABASE='+DBNAME+';Trusted_Connection='+TRUSTED_CONNECTION